name: tfLint
description: 'This action runs the tflint action'

runs:
  using: "composite"
  steps:
    - name: Lint Code Base
      uses: terraform-linters/setup-tflint@v2
      with:
        tflint_version: v0.38.1
    - name: Run tflint
      shell: bash
      run: tflint -f compact
