name: 'Lint Code Base'
description: 'This action runs the Super-Linter action'


runs:
  using: "composite"
  steps:
    - name: Lint Code Base
      uses: github/super-linter@v4
      env:
        OUTPUT_FOLDER:
        VALIDATE_TERRAFORM: true
        VALIDATE_YAML: true
        DEFAULT_BRANCH: main
